import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/header";
import { Roboto } from "next/font/google";

const font = Roboto({ 
  subsets: ['latin' , 'latin-ext'],
  weight: ["300", "500", "700", "900"], 
  style: 'normal', 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} overflow-x-hidden`}
      >
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
